finchcollector/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('main_app.urls'))
]

main_app/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('', views.home, name='home'),
    path('about/', views.about, name='about'),
    path('finches/', views.finches_index, name='index'),
    path('finches/<int:finch_id>', views.finch_detail, name='detail'),
    path('finches/create/', views.FinchCreate.as_view(), name='finches_create'),
    path('finches/<int:pk>/update/', views.FinchUpdate.as_view(), name="finches_update"),
    path('finches/<int:pk>/delete/', views.FinchDelete.as_view(), name="finches_delete"),
    path('finches/<int:finch_id>/add_feeding', views.add_feeding, name='add_feeding'),
    path('hats/', views.HatList.as_view(), name='hats_index'),
    path('hats/<int:pk>/', views.HatDetail.as_view(), name='hats_detail'),
    path('hats/create/', views.HatCreate.as_view(), name='hats_create'),
    path('hats/<int:pk>/update/', views.HatUpdate.as_view(), name='hats_update'),
    path('hats/<int:pk>/delete/', views.HatDelete.as_view(), name='hats_delete'),
    path('finchs/<int:finch_id>/assoc_hat/<int:hat_id>/', views.assoc_hat, name='assoc_hat'),
    path('finchs/<int:finch_id>/unassoc_hat/<int:hat_id>/', views.unassoc_hat, name='unassoc_hat')
]

main_app/models.py
from django.db import models
from django.urls import reverse

# Create your models here.
class Hat(models.Model):
    type = models.CharField(max_length=100)
    color = models.CharField(max_length=50)

    def __str__(self):
        return self.name
     
    def get_absolute_url(self):
        return reverse('hats_detail', kwargs={'pk': self.id})

class Finch(models.Model):
    type = models.CharField(max_length=100)
    color = models.CharField(max_length=100)
    description = models.TextField(max_length=250)
    hats = models.ManyToManyField(Hat)

    def __str__(self):
            return self.type

    def get_absolute_url(self):
        return reverse("detail", kwargs={"finch_id": self.id})
    
class Feeding(models.Model):
    MEALS = (
        ('B', 'Breakfast'),
        ('L', 'Lunch'),
        ('D', 'Dinner')
    )
    date = models.DateField('feeding date')
    meal = models.CharField(max_length=1, choices=MEALS, default='B')
    finch = models.ForeignKey(Finch, on_delete=models.CASCADE)

    def __str__(self):
        return f'{self.get_meal_display()} on {self.date}'
    
    class Meta:
        ordering = ('-date',)
    

main_app/forms.py
from django.forms import ModelForm
from .models import Feeding

class FeedingForm(ModelForm):
    class Meta:
        model = Feeding
        fields = ('date', 'meal')

main_app/views.py
from django.shortcuts import render, redirect
from .models import Finch, Hat
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.views.generic import ListView, DetailView
from .forms import FeedingForm

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'about.html')

def finches_index(request):
    finches = Finch.objects.all()
    return render(request, 'finches/index.html', {
        'finches': finches
    })

def finch_detail(request, finch_id):
    finch = Finch.objects.get(id=finch_id)
    id_list = finch.hats.all().values_list('id')
    hat_that_finch_doesnt_have = Hat.objects.exclude(id__in=id_list)
    feeding_form = FeedingForm()
    return render(request, 'finches/detail.html', {
        'finch': finch,
        'feeding_form': feeding_form,
        'hats': hat_that_finch_doesnt_have
    })

def assoc_hat(request, finch_id, hat_id):
  Finch.objects.get(id=finch_id).hats.add(hat_id)
  return redirect('detail', finch_id=finch_id)

def unassoc_hat(request, finch_id, hat_id):
  Finch.objects.get(id=finch_id).hats.remove(hat_id)
  return redirect('detail', finch_id=finch_id)

def add_feeding(request, finch_id):
    submitted_form = FeedingForm(request.POST)
    if submitted_form.is_valid():
        new_feeding = submitted_form.save(commit=False)
        new_feeding.finch_id = finch_id
        new_feeding.save()
    return redirect('detail', finch_id=finch_id)

class FinchCreate(CreateView):
    model = Finch
    fields = ['type', 'color', 'description']

class FinchUpdate(UpdateView):
    model = Finch
    fields = ['type', 'color', 'description']

class FinchDelete(DeleteView):
    model = Finch
    success_url = '/finches/'

class HatList(ListView):
    model = Hat

class HatDetail(DetailView):
    model = Hat

class HatCreate(CreateView):
    model = Hat
    fields = '__all__'

class HatUpdate(UpdateView):
    model = Hat
    fields = ['type', 'color']

class HatDelete(DeleteView):
    model = Hat
    success_url = '/hats'

main_app/templates/about.html
{% extends "base.html" %}

{% block content %}
    <h1>About the Finch Collector</h1>
    <hr>
    <p>Hire the Finch Collector</p>
{% endblock %}

main_app/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta http-equiv="X-UA-Compatible" content="ie=edge">
  <title>Finch Collector</title>
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/css/materialize.min.css">
  <link rel="stylesheet" href="{% static 'css/style.css' %}">
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/1.0.0/js/materialize.min.js"></script>
</head>
<body>
  <header class="navbar-fixed">
    <nav>
      <div class="nav-wrapper">
        <ul>
          <li><a href="/" class="left brand-logo">&nbsp;&nbsp;Finch Collector</a></li>
        </ul>
        <ul class="right">
          <li><a href="{% url "about" %}">About</a></li>
          <li><a href="{% url 'hats_create' %}">Add a Hat</a></li>
          <li><a href="{% url 'hats_index' %}">View All Hats</a></li>
          <li><a href="{% url "finches_create" %}">Add a Finch</a></li>
          <li><a href="{% url "index" %}">View All My Finchess</a></li>
        </ul>
      </div>
    </nav>
  </header>
  <main class="container">
    {% block content %}
    {% endblock %}
  </main>
  <footer class="page-footer">
    <div class="right">All Rights Reserved, &copy; 2021 Finch Collector &nbsp;</div>
  </footer>
</body>
</html>

main_app/templates/finches/detail.html
{% extends "base.html" %}

{% block content %}
<h1>Finch Detail</h1>
    

    <div class="row">
        <div class="col s6">
            <div class="card">
                <div class="card-content">
                    <span class="card-title">{{ finch.type }}</span>
                    <p>Color: {{ finch.color }}</p>
                    <p>Description: {{ finch.description }}</p>
                </div>
                <div class="card-action">
                    <a href="{% url "finches_update" finch.id %}">Edit</a>
                    <a href="{% url "finches_delete" finch.id %}">Delete</a>
                </div>
            </div>
        </div>
        <div class="col s6">
            <form action="{% url "add_feeding" finch.id %}" method="POST">
                {% csrf_token %}
                {{ feeding_form.as_p }}
                <input type="submit" value="Add Feeding" class="btn blue">
            </form>
            <table class="striped">
                <thead>
                    <tr>
                        <th>Date</th>
                        <th>Meal</th>
                    </tr>
                </thead>
                <tbody>
                    {% for feeding in finch.feeding_set.all %}
                        <tr>
                            <td>{{ feeding.date }}</td>
                            <td>{{ feeding.get_meal_display }}</td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        </div>
    </div>

    <div class="row">
        <div class="col s6">
          <h3>{{ finch.type }}'s Toys</h3>
          {% if finch.hats.count %}
          {% for hat in finch.hats.all %}
          <div class="card">
            <div class="card-content">
              <span class="card-title">
                A <span class="{{ hat.color.lower }}-text">{{ hat.color }}</span> {{ hat.type }}
              </span>
            </div>
            <div class="card-action">
              <form action="{% url "unassoc_hat" finch.id hat.id %}" method="POST">
                {% csrf_token %}
                <input type="submit" value="Remove" class="btn red">
              </form>
            </div>
          </div>
          {% endfor %}
          {% else %}
          <h5>{{ finch.type }} has no hats yet</h5>
          {% endif %}
        </div>
        <div class="col s6">
          <h3>Available Hats</h3>
          {% for hat in hats %}
          <div class="card">
            <div class="card-content">
              <span class="card-title">
                A <span class="{{ hat.color.lower }}-text">{{ hat.color }}</span> {{ hat.type }}
              </span>
            </div>
            <div class="card-action">
              <form action="{% url "assoc_hat" finch.id hat.id %}" method="POST">
                {% csrf_token %}
                <input type="submit" value="Add" class="btn green">
              </form>
            </div>
          </div>
          {% endfor %}
        </div>
      </div>

    <script>
        const dateEl = document.getElementById('id_date');
        const selectEl = document.getElementById('id_meal');
    
        M.Datepicker.init(dateEl, {
            format: 'yyyy-mm-dd',
            defaultDate: new Date(),
            setDefaultDate: true,
            autoClose: true
        });
    
        M.FormSelect.init(selectEl);
     
    </script>

{% endblock  %}

main_app/templates/finches/index.html
{% extends "base.html" %}

{% block content %}
<h1>Finch List</h1>

{% for finch in finches %}
<a href="/finches/{{ finch.id }}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ finch.type }}</span>
            <p>Color: {{ finch.color }}</p>
            <p>Description: {{ finch.description }}</p>
        </div>
    </div>
</a>
{% endfor %}

{% endblock  %}

main_app/templates/home.html
{% extends "base.html" %}

{% block content %}
<h1>Finch Collector</h1>
{% endblock  %}

main_app/templates/main_app/finch_confirm_delete.html
{% extends "base.html" %}

{% block content %}

<h1>Are you sure you want to delete {{ object.type }}?</h1>

<form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes, I want to Delete {{ object.name }}" class="btn red">
    <a class="btn green" href="{% url "detail" object.id %}">Cancel</a>
</form>

{% endblock  %}

main_app/templates/main_app/finch_form.html
{% extends "base.html" %}

{% block content %}
{% if object %}
<h1>Update {{ finch.type }}'s Detail</h1>
{% else %}
<h1>Create a Finch</h1>
{% endif %}

<form action="" method="POST">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Submit" class="btn">
</form>

{% endblock  %}

main_app/templates/main_app/hat_confirm_delete.html
{% extends 'base.html' %}

{% block content %}
  <h1>Delete Hat</h1>

  <h4>Are you sure you want to delete <span class="teal-text">{{ object.name }}</span>?</h4>

  <form action="" method="POST">
    {% csrf_token %}
    <input type="submit" value="Yes - Delete!" class="btn">
    <a href="{% url 'hats_detail' object.id %}">Cancel</a>
  </form>
{% endblock %}

main_app/templates/main_app/hat_detail.html
{% extends 'base.html' %}
{% block content %}

<h1>Hat Details</h1>

<div class="row">
  <div class="col s6 col-offset-3">
    <div class="card">
      <div class="card-content">
        <span class="card-title">{{ hat.type }}</span>
        <p>Color: {{ hat.color }}</p>
      </div>
      <div class="card-action">
        <a href="{% url 'hats_update' hat.id %}">Edit</a>
        <a href="{% url 'hats_delete' hat.id %}">Delete</a>
      </div>
    </div>
  </div>
</div>
{% endblock %}

main_app/templates/main_app/hat_form.html
{% extends 'base.html' %}

{% block content %}
  {% if object %}
    <h1>Edit <span class="teal-text">{{object.name}}</span></h1>
  {% else %}
    <h1>Add Hat</h1>
  {% endif %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
      {{ form.as_table }}
    </table>
    <input type="submit" value="Submit!" class="btn">
  </form>
{% endblock %}

main_app/templates/main_app/hat_list.html
{% extends 'base.html' %}
{% block content %}

<h1>Hat List</h1>

{% for hat in hat_list %}
  <a href="{% url 'hats_detail' hat.id %}">
    <div class="card">
        <div class="card-content">
            <span class="card-title">{{ hat.name }}</span>
            <p>Color: {{ hat.color }}</p>
        </div>
    </div>
  </a>
{% endfor %}

{% endblock %}